---
title: "Draft"
author: "Bulun Te"
date: "2024-04-23"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
---



## Data generation

```{r}

setwd(here::here())
load("CPD.rda")
library(readxl)
mamo_data = read.csv("mamo_data.csv")
library(purrr)

if (!requireNamespace("logistf", quietly = TRUE)) {
  install.packages("logistf")
}
library(logistf)
library(dplyr)
library(corrplot)

kirc <- Data$KIRC

names(kirc) <- make.names(names(kirc))

kirc <- kirc %>% select(
  -Patient.ID,
  -Hormone.Receptor
) %>% na.omit()

kirc <- kirc %>% mutate(
  state_1 = ifelse(Pathologic.Stage %in% c("i","ia","ib"), 1, 0),
  state_2 = ifelse(Pathologic.Stage %in% c("ii","iia","iib"),1,0)
) %>% select(-Pathologic.Stage)

# glm(Survival.Indicator ~ .,data=kirc,family = binomial) %>% summary()


lusc <- Data$LUSC

names(lusc) <- make.names(names(lusc))

lusc <- lusc %>% select(
  -Patient.ID,
  -Hormone.Receptor
) %>% na.omit()

lusc <- lusc %>% mutate(
  state_1 = ifelse(Pathologic.Stage %in% c("i","ia","ib"), 1, 0),
  state_2 = ifelse(Pathologic.Stage %in% c("ii","iia","iib"),1,0)
) %>% select(-Pathologic.Stage)


data_bind_2 = rbind(kirc,lusc)

```

```{r}

library(ResourceSelection)

```

## Two Dataset focusing on interaction

```{r}


glm(
  Survival.Indicator ~ Apoptosis *  Cancer.Code + Gender + Age.at.Diagnosis..Years. + state_1 + state_2,
  data = data_bind_2,
  family = binomial
) -> temp_model

summary(temp_model)
hoslem.test(temp_model$y, temp_model$fitted.values, g=10)

car::vif(temp_model)


```



## Two dataset, doing subgroup analysis


```{r}

glm(
  Survival.Indicator ~ (Apoptosis+ Gender + Age.at.Diagnosis..Years. + state_1 + state_2) * Cancer.Code,
  data = data_bind_2,
  family = binomial
)-> temp_model

summary(temp_model)
hoslem.test(temp_model$y, temp_model$fitted.values, g=10)


car::vif(temp_model)

```


###  Kidney Cancer

```{r}

glm(
  Survival.Indicator ~ (Apoptosis+ Gender + Age.at.Diagnosis..Years. + state_1 + state_2) ,
  data = kirc,
  family = binomial
) -> temp_model

summary(temp_model)
hoslem.test(temp_model$y, temp_model$fitted.values, g=10)

car::vif(temp_model)

```



### Lung Cancer


```{r}

glm(
  Survival.Indicator ~ (Apoptosis+ Gender + Age.at.Diagnosis..Years. + state_1 + state_2) ,
  data = lusc,
  family = binomial
)-> temp_model

summary(temp_model)
hoslem.test(temp_model$y, temp_model$fitted.values, g=10)


car::vif(temp_model)

```


